=== yijunyu/protoyacc/sql/sql2.dtd
<!ELEMENT sql_list (sql,CHAR59)>
<!ELEMENT sql_list (sql_list,sql,CHAR59)>
<!ELEMENT sql (schema)>
<!ELEMENT schema (CREATE,SCHEMA,AUTHORIZATION,user,opt_schema_element_list)>
<!ELEMENT opt_schema_element_list EMPTY><!ELEMENT opt_schema_element_list (schema_element_list)>
<!ELEMENT schema_element_list (schema_element)>
<!ELEMENT schema_element_list (schema_element_list,schema_element)>
<!ELEMENT schema_element (base_table_def)>
<!ELEMENT schema_element (view_def)>
<!ELEMENT schema_element (privilege_def)>
<!ELEMENT base_table_def (CREATE,TABLE,table,CHAR40,base_table_element_commalist,CHAR41)>
<!ELEMENT base_table_element_commalist (base_table_element)>
<!ELEMENT base_table_element_commalist (base_table_element_commalist,CHAR44,base_table_element)>
<!ELEMENT base_table_element (column_def)>
<!ELEMENT base_table_element (table_constraint_def)>
<!ELEMENT column_def (column,data_type,column_def_opt_list)>
<!ELEMENT column_def_opt_list EMPTY><!ELEMENT column_def_opt_list (column_def_opt_list,column_def_opt)>
<!ELEMENT column_def_opt (NOT,NULLX)>
<!ELEMENT column_def_opt (NOT,NULLX,UNIQUE)>
<!ELEMENT column_def_opt (NOT,NULLX,PRIMARY,KEY)>
<!ELEMENT column_def_opt (DEFAULT,literal)>
<!ELEMENT column_def_opt (DEFAULT,NULLX)>
<!ELEMENT column_def_opt (DEFAULT,USER)>
<!ELEMENT column_def_opt (CHECK,CHAR40,search_condition,CHAR41)>
<!ELEMENT column_def_opt (REFERENCES,table)>
<!ELEMENT column_def_opt (REFERENCES,table,CHAR40,column_commalist,CHAR41)>
<!ELEMENT table_constraint_def (UNIQUE,CHAR40,column_commalist,CHAR41)>
<!ELEMENT table_constraint_def (PRIMARY,KEY,CHAR40,column_commalist,CHAR41)>
<!ELEMENT table_constraint_def (FOREIGN,KEY,CHAR40,column_commalist,CHAR41,REFERENCES,table)>
<!ELEMENT table_constraint_def (FOREIGN,KEY,CHAR40,column_commalist,CHAR41,REFERENCES,table,CHAR40,column_commalist,CHAR41)>
<!ELEMENT table_constraint_def (CHECK,CHAR40,search_condition,CHAR41)>
<!ELEMENT column_commalist (column)>
<!ELEMENT column_commalist (column_commalist,CHAR44,column)>
<!ELEMENT view_def (CREATE,VIEW,table,opt_column_commalist,AS,query_spec,opt_with_check_option)>
<!ELEMENT opt_with_check_option EMPTY><!ELEMENT opt_with_check_option (WITH,CHECK,OPTION)>
<!ELEMENT opt_column_commalist EMPTY><!ELEMENT opt_column_commalist (CHAR40,column_commalist,CHAR41)>
<!ELEMENT privilege_def (GRANT,privileges,ON,table,TO,grantee_commalist,opt_with_grant_option)>
<!ELEMENT opt_with_grant_option EMPTY><!ELEMENT opt_with_grant_option (WITH,GRANT,OPTION)>
<!ELEMENT privileges (ALL,PRIVILEGES)>
<!ELEMENT privileges (ALL)>
<!ELEMENT privileges (operation_commalist)>
<!ELEMENT operation_commalist (operation)>
<!ELEMENT operation_commalist (operation_commalist,CHAR44,operation)>
<!ELEMENT operation (SELECT)>
<!ELEMENT operation (INSERT)>
<!ELEMENT operation (DELETE)>
<!ELEMENT operation (UPDATE,opt_column_commalist)>
<!ELEMENT operation (REFERENCES,opt_column_commalist)>
<!ELEMENT grantee_commalist (grantee)>
<!ELEMENT grantee_commalist (grantee_commalist,CHAR44,grantee)>
<!ELEMENT grantee (PUBLIC)>
<!ELEMENT grantee (user)>
<!ELEMENT sql (cursor_def)>
<!ELEMENT cursor_def (DECLARE,cursor,CURSOR,FOR,query_exp,opt_order_by_clause)>
<!ELEMENT opt_order_by_clause EMPTY><!ELEMENT opt_order_by_clause (ORDER,BY,ordering_spec_commalist)>
<!ELEMENT ordering_spec_commalist (ordering_spec)>
<!ELEMENT ordering_spec_commalist (ordering_spec_commalist,CHAR44,ordering_spec)>
<!ELEMENT ordering_spec (INTNUM,opt_asc_desc)>
<!ELEMENT ordering_spec (column_ref,opt_asc_desc)>
<!ELEMENT opt_asc_desc EMPTY><!ELEMENT opt_asc_desc (ASC)>
<!ELEMENT opt_asc_desc (DESC)>
<!ELEMENT sql (manipulative_statement)>
<!ELEMENT manipulative_statement (close_statement)>
<!ELEMENT manipulative_statement (commit_statement)>
<!ELEMENT manipulative_statement (delete_statement_positioned)>
<!ELEMENT manipulative_statement (delete_statement_searched)>
<!ELEMENT manipulative_statement (fetch_statement)>
<!ELEMENT manipulative_statement (insert_statement)>
<!ELEMENT manipulative_statement (open_statement)>
<!ELEMENT manipulative_statement (rollback_statement)>
<!ELEMENT manipulative_statement (select_statement)>
<!ELEMENT manipulative_statement (update_statement_positioned)>
<!ELEMENT manipulative_statement (update_statement_searched)>
<!ELEMENT close_statement (CLOSE,cursor)>
<!ELEMENT commit_statement (COMMIT,WORK)>
<!ELEMENT delete_statement_positioned (DELETE,FROM,table,WHERE,CURRENT,OF,cursor)>
<!ELEMENT delete_statement_searched (DELETE,FROM,table,opt_where_clause)>
<!ELEMENT fetch_statement (FETCH,cursor,INTO,target_commalist)>
<!ELEMENT insert_statement (INSERT,INTO,table,opt_column_commalist,values_or_query_spec)>
<!ELEMENT values_or_query_spec (VALUES,CHAR40,insert_atom_commalist,CHAR41)>
<!ELEMENT values_or_query_spec (query_spec)>
<!ELEMENT insert_atom_commalist (insert_atom)>
<!ELEMENT insert_atom_commalist (insert_atom_commalist,CHAR44,insert_atom)>
<!ELEMENT insert_atom (atom)>
<!ELEMENT insert_atom (NULLX)>
<!ELEMENT open_statement (OPEN,cursor)>
<!ELEMENT rollback_statement (ROLLBACK,WORK)>
<!ELEMENT select_statement (SELECT,opt_all_distinct,selection,INTO,target_commalist,table_exp)>
<!ELEMENT opt_all_distinct EMPTY><!ELEMENT opt_all_distinct (ALL)>
<!ELEMENT opt_all_distinct (DISTINCT)>
<!ELEMENT update_statement_positioned (UPDATE,table,SET,assignment_commalist,WHERE,CURRENT,OF,cursor)>
<!ELEMENT assignment_commalist EMPTY><!ELEMENT assignment_commalist (assignment)>
<!ELEMENT assignment_commalist (assignment_commalist,CHAR44,assignment)>
<!ELEMENT assignment (column,CHAR61,scalar_exp)>
<!ELEMENT assignment (column,CHAR61,NULLX)>
<!ELEMENT update_statement_searched (UPDATE,table,SET,assignment_commalist,opt_where_clause)>
<!ELEMENT target_commalist (target)>
<!ELEMENT target_commalist (target_commalist,CHAR44,target)>
<!ELEMENT target (parameter_ref)>
<!ELEMENT opt_where_clause EMPTY><!ELEMENT opt_where_clause (where_clause)>
<!ELEMENT query_exp (query_term)>
<!ELEMENT query_exp (query_exp,UNION,query_term)>
<!ELEMENT query_exp (query_exp,UNION,ALL,query_term)>
<!ELEMENT query_term (query_spec)>
<!ELEMENT query_term (CHAR40,query_exp,CHAR41)>
<!ELEMENT query_spec (SELECT,opt_all_distinct,selection,table_exp)>
<!ELEMENT selection (scalar_exp_commalist)>
<!ELEMENT selection (CHAR42)>
<!ELEMENT table_exp (from_clause,opt_where_clause,opt_group_by_clause,opt_having_clause)>
<!ELEMENT from_clause (FROM,table_ref_commalist)>
<!ELEMENT table_ref_commalist (table_ref)>
<!ELEMENT table_ref_commalist (table_ref_commalist,CHAR44,table_ref)>
<!ELEMENT table_ref (table)>
<!ELEMENT table_ref (table,range_variable)>
<!ELEMENT where_clause (WHERE,search_condition)>
<!ELEMENT opt_group_by_clause EMPTY><!ELEMENT opt_group_by_clause (GROUP,BY,column_ref_commalist)>
<!ELEMENT column_ref_commalist (column_ref)>
<!ELEMENT column_ref_commalist (column_ref_commalist,CHAR44,column_ref)>
<!ELEMENT opt_having_clause EMPTY><!ELEMENT opt_having_clause (HAVING,search_condition)>
<!ELEMENT search_condition EMPTY><!ELEMENT search_condition (search_condition,OR,search_condition)>
<!ELEMENT search_condition (search_condition,AND,search_condition)>
<!ELEMENT search_condition (NOT,search_condition)>
<!ELEMENT search_condition (CHAR40,search_condition,CHAR41)>
<!ELEMENT search_condition (predicate)>
<!ELEMENT predicate (comparison_predicate)>
<!ELEMENT predicate (between_predicate)>
<!ELEMENT predicate (like_predicate)>
<!ELEMENT predicate (test_for_null)>
<!ELEMENT predicate (in_predicate)>
<!ELEMENT predicate (all_or_any_predicate)>
<!ELEMENT predicate (existence_test)>
<!ELEMENT comparison_predicate (scalar_exp,COMPARISON,scalar_exp)>
<!ELEMENT comparison_predicate (scalar_exp,COMPARISON,subquery)>
<!ELEMENT between_predicate (scalar_exp,NOT,BETWEEN,scalar_exp,AND,scalar_exp)>
<!ELEMENT between_predicate (scalar_exp,BETWEEN,scalar_exp,AND,scalar_exp)>
<!ELEMENT like_predicate (scalar_exp,NOT,LIKE,atom,opt_escape)>
<!ELEMENT like_predicate (scalar_exp,LIKE,atom,opt_escape)>
<!ELEMENT opt_escape EMPTY><!ELEMENT opt_escape (ESCAPE,atom)>
<!ELEMENT test_for_null (column_ref,IS,NOT,NULLX)>
<!ELEMENT test_for_null (column_ref,IS,NULLX)>
<!ELEMENT in_predicate (scalar_exp,NOT,IN,CHAR40,subquery,CHAR41)>
<!ELEMENT in_predicate (scalar_exp,IN,CHAR40,subquery,CHAR41)>
<!ELEMENT in_predicate (scalar_exp,NOT,IN,CHAR40,atom_commalist,CHAR41)>
<!ELEMENT in_predicate (scalar_exp,IN,CHAR40,atom_commalist,CHAR41)>
<!ELEMENT atom_commalist (atom)>
<!ELEMENT atom_commalist (atom_commalist,CHAR44,atom)>
<!ELEMENT all_or_any_predicate (scalar_exp,COMPARISON,any_all_some,subquery)>
<!ELEMENT any_all_some (ANY)>
<!ELEMENT any_all_some (ALL)>
<!ELEMENT any_all_some (SOME)>
<!ELEMENT existence_test (EXISTS,subquery)>
<!ELEMENT subquery (CHAR40,SELECT,opt_all_distinct,selection,table_exp,CHAR41)>
<!ELEMENT scalar_exp (scalar_exp,CHAR43,scalar_exp)>
<!ELEMENT scalar_exp (scalar_exp,CHAR45,scalar_exp)>
<!ELEMENT scalar_exp (scalar_exp,CHAR42,scalar_exp)>
<!ELEMENT scalar_exp (scalar_exp,CHAR47,scalar_exp)>
<!ELEMENT scalar_exp (CHAR43,scalar_exp)>
<!ELEMENT scalar_exp (CHAR45,scalar_exp)>
<!ELEMENT scalar_exp (atom)>
<!ELEMENT scalar_exp (column_ref)>
<!ELEMENT scalar_exp (function_ref)>
<!ELEMENT scalar_exp (CHAR40,scalar_exp,CHAR41)>
<!ELEMENT scalar_exp_commalist (scalar_exp)>
<!ELEMENT scalar_exp_commalist (scalar_exp_commalist,CHAR44,scalar_exp)>
<!ELEMENT atom (parameter_ref)>
<!ELEMENT atom (literal)>
<!ELEMENT atom (USER)>
<!ELEMENT parameter_ref (parameter)>
<!ELEMENT parameter_ref (parameter,parameter)>
<!ELEMENT parameter_ref (parameter,INDICATOR,parameter)>
<!ELEMENT function_ref (AMMSC,CHAR40,CHAR42,CHAR41)>
<!ELEMENT function_ref (AMMSC,CHAR40,DISTINCT,column_ref,CHAR41)>
<!ELEMENT function_ref (AMMSC,CHAR40,ALL,scalar_exp,CHAR41)>
<!ELEMENT function_ref (AMMSC,CHAR40,scalar_exp,CHAR41)>
<!ELEMENT literal (STRING)>
<!ELEMENT literal (INTNUM)>
<!ELEMENT literal (APPROXNUM)>
<!ELEMENT table (NAME)>
<!ELEMENT table (NAME,CHAR46,NAME)>
<!ELEMENT column_ref (NAME)>
<!ELEMENT column_ref (NAME,CHAR46,NAME)>
<!ELEMENT column_ref (NAME,CHAR46,NAME,CHAR46,NAME)>
<!ELEMENT data_type (CHARACTER)>
<!ELEMENT data_type (CHARACTER,CHAR40,INTNUM,CHAR41)>
<!ELEMENT data_type (NUMERIC)>
<!ELEMENT data_type (NUMERIC,CHAR40,INTNUM,CHAR41)>
<!ELEMENT data_type (NUMERIC,CHAR40,INTNUM,CHAR44,INTNUM,CHAR41)>
<!ELEMENT data_type (DECIMAL)>
<!ELEMENT data_type (DECIMAL,CHAR40,INTNUM,CHAR41)>
<!ELEMENT data_type (DECIMAL,CHAR40,INTNUM,CHAR44,INTNUM,CHAR41)>
<!ELEMENT data_type (INTEGER)>
<!ELEMENT data_type (SMALLINT)>
<!ELEMENT data_type (FLOAT)>
<!ELEMENT data_type (FLOAT,CHAR40,INTNUM,CHAR41)>
<!ELEMENT data_type (REAL)>
<!ELEMENT data_type (DOUBLE,PRECISION)>
<!ELEMENT column (NAME)>
<!ELEMENT cursor (NAME)>
<!ELEMENT parameter (PARAMETER)>
<!ELEMENT range_variable (NAME)>
<!ELEMENT user (NAME)>
<!ELEMENT sql (WHENEVER,NOT,FOUND,when_action)>
<!ELEMENT sql (WHENEVER,SQLERROR,when_action)>
<!ELEMENT when_action (GOTO,NAME)>
<!ELEMENT when_action (CONTINUE)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT STRING (#PCDATA)>
<!ELEMENT INTNUM (#PCDATA)>
<!ELEMENT APPROXNUM (#PCDATA)>
<!ELEMENT OR (#PCDATA)>
<!ELEMENT AND (#PCDATA)>
<!ELEMENT NOT (#PCDATA)>
<!ELEMENT COMPARISON (#PCDATA)>
<!ELEMENT CHAR43 (#PCDATA)>
<!ELEMENT CHAR45 (#PCDATA)>
<!ELEMENT CHAR42 (#PCDATA)>
<!ELEMENT CHAR47 (#PCDATA)>
<!ELEMENT UMINUS (#PCDATA)>
<!ELEMENT ALL (#PCDATA)>
<!ELEMENT AMMSC (#PCDATA)>
<!ELEMENT ANY (#PCDATA)>
<!ELEMENT AS (#PCDATA)>
<!ELEMENT ASC (#PCDATA)>
<!ELEMENT AUTHORIZATION (#PCDATA)>
<!ELEMENT BETWEEN (#PCDATA)>
<!ELEMENT BY (#PCDATA)>
<!ELEMENT CHARACTER (#PCDATA)>
<!ELEMENT CHECK (#PCDATA)>
<!ELEMENT CLOSE (#PCDATA)>
<!ELEMENT COMMIT (#PCDATA)>
<!ELEMENT CONTINUE (#PCDATA)>
<!ELEMENT CREATE (#PCDATA)>
<!ELEMENT CURRENT (#PCDATA)>
<!ELEMENT CURSOR (#PCDATA)>
<!ELEMENT DECIMAL (#PCDATA)>
<!ELEMENT DECLARE (#PCDATA)>
<!ELEMENT DEFAULT (#PCDATA)>
<!ELEMENT DELETE (#PCDATA)>
<!ELEMENT DESC (#PCDATA)>
<!ELEMENT DISTINCT (#PCDATA)>
<!ELEMENT DOUBLE (#PCDATA)>
<!ELEMENT ESCAPE (#PCDATA)>
<!ELEMENT EXISTS (#PCDATA)>
<!ELEMENT FETCH (#PCDATA)>
<!ELEMENT FLOAT (#PCDATA)>
<!ELEMENT FOR (#PCDATA)>
<!ELEMENT FOREIGN (#PCDATA)>
<!ELEMENT FOUND (#PCDATA)>
<!ELEMENT FROM (#PCDATA)>
<!ELEMENT GOTO (#PCDATA)>
<!ELEMENT GRANT (#PCDATA)>
<!ELEMENT GROUP (#PCDATA)>
<!ELEMENT HAVING (#PCDATA)>
<!ELEMENT IN (#PCDATA)>
<!ELEMENT INDICATOR (#PCDATA)>
<!ELEMENT INSERT (#PCDATA)>
<!ELEMENT INTEGER (#PCDATA)>
<!ELEMENT INTO (#PCDATA)>
<!ELEMENT IS (#PCDATA)>
<!ELEMENT KEY (#PCDATA)>
<!ELEMENT LANGUAGE (#PCDATA)>
<!ELEMENT LIKE (#PCDATA)>
<!ELEMENT NULLX (#PCDATA)>
<!ELEMENT NUMERIC (#PCDATA)>
<!ELEMENT OF (#PCDATA)>
<!ELEMENT ON (#PCDATA)>
<!ELEMENT OPEN (#PCDATA)>
<!ELEMENT OPTION (#PCDATA)>
<!ELEMENT ORDER (#PCDATA)>
<!ELEMENT PARAMETER (#PCDATA)>
<!ELEMENT PRECISION (#PCDATA)>
<!ELEMENT PRIMARY (#PCDATA)>
<!ELEMENT PRIVILEGES (#PCDATA)>
<!ELEMENT PROCEDURE (#PCDATA)>
<!ELEMENT PUBLIC (#PCDATA)>
<!ELEMENT REAL (#PCDATA)>
<!ELEMENT REFERENCES (#PCDATA)>
<!ELEMENT ROLLBACK (#PCDATA)>
<!ELEMENT SCHEMA (#PCDATA)>
<!ELEMENT SELECT (#PCDATA)>
<!ELEMENT SET (#PCDATA)>
<!ELEMENT SMALLINT (#PCDATA)>
<!ELEMENT SOME (#PCDATA)>
<!ELEMENT SQLCODE (#PCDATA)>
<!ELEMENT SQLERROR (#PCDATA)>
<!ELEMENT TABLE (#PCDATA)>
<!ELEMENT TO (#PCDATA)>
<!ELEMENT UNION (#PCDATA)>
<!ELEMENT UNIQUE (#PCDATA)>
<!ELEMENT UPDATE (#PCDATA)>
<!ELEMENT USER (#PCDATA)>
<!ELEMENT VALUES (#PCDATA)>
<!ELEMENT VIEW (#PCDATA)>
<!ELEMENT WHENEVER (#PCDATA)>
<!ELEMENT WHERE (#PCDATA)>
<!ELEMENT WITH (#PCDATA)>
<!ELEMENT WORK (#PCDATA)>
<!ELEMENT CHAR59 (#PCDATA)>
<!ELEMENT CHAR40 (#PCDATA)>
<!ELEMENT CHAR41 (#PCDATA)>
<!ELEMENT CHAR44 (#PCDATA)>
<!ELEMENT CHAR61 (#PCDATA)>
<!ELEMENT CHAR46 (#PCDATA)>

=== yijunyu/protoyacc/sql/test.sql2.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="yaxx.xsl"?><!DOCTYPE sql_list SYSTEM "sql2.dtd">
<yaxx:sql_list xmlns:yaxx="urn:YAcc-Xml-eXtension">
<yaxx:sql>
<yaxx:manipulative_statement>
<yaxx:select_statement>
<yaxx:SELECT>SELECT</yaxx:SELECT>
<yaxx:opt_all_distinct>
<yaxx:DISTINCT>DISTINCT</yaxx:DISTINCT>
</yaxx:opt_all_distinct>
<yaxx:selection>
<yaxx:scalar_exp_commalist>
<yaxx:scalar_exp>
<yaxx:column_ref>
<yaxx:NAME>key</yaxx:NAME>
</yaxx:column_ref>
</yaxx:scalar_exp>
</yaxx:scalar_exp_commalist>
</yaxx:selection>
<yaxx:INTO>INTO</yaxx:INTO>
<yaxx:target_commalist>
<yaxx:target>
<yaxx:parameter_ref>
<yaxx:parameter>
<yaxx:PARAMETER>:name</yaxx:PARAMETER>
</yaxx:parameter>
</yaxx:parameter_ref>
</yaxx:target>
</yaxx:target_commalist>
<yaxx:table_exp>
<yaxx:from_clause>
<yaxx:FROM>FROM</yaxx:FROM>
<yaxx:table_ref_commalist>
<yaxx:table_ref>
<yaxx:table>
<yaxx:NAME>student</yaxx:NAME>
</yaxx:table>
</yaxx:table_ref>
</yaxx:table_ref_commalist>
</yaxx:from_clause>
<yaxx:opt_where_clause>
</yaxx:opt_where_clause>
<yaxx:opt_group_by_clause>
</yaxx:opt_group_by_clause>
<yaxx:opt_having_clause>
</yaxx:opt_having_clause>
</yaxx:table_exp>
</yaxx:select_statement>
</yaxx:manipulative_statement>
</yaxx:sql>
<yaxx:CHAR59>;</yaxx:CHAR59>
</yaxx:sql_list>
